[tools]
bun = "latest"
copier = "latest"
github-cli = "latest"
glab = "latest"
helm = "3"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
opentofu = "latest"
talosctl = "latest"
terragrunt = "latest"
