format = """
$directory\
$git_branch\
$git_state\
$git_status\
$aws\
$kubernetes\
$python\
$terraform\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$character"""


[aws]
format = 'on [☁️ ($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
format = 'on [⛵ $context \($namespace\)](bold dimmed blue) '
disabled = false
